runtime: php
env: flex

runtime_config: 
       document_root: public

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: production
    APP_KEY: base64:P4OKilk0oWjgOCPoD5CzPrDXJg1o+m14/AXzF2uk8s0=
    APP_NAME: "GCP-Portfolio"

    DB_DATABASE: portfolio-1
    DB_USERNAME: root
    DB_PASSWORD: rizqy
    DB_SOCKET: '/cloudsql/gcp-portfolio-sql'

    LOG_LEVEL: debug

beta_settings:
    cloud_sql_instances: 'myportfolio-412010:asia-southeast1:gcp-portfolio-sql'
